---
jobs:
- name: build-resource-image
  public: true
  serial: true
  plan:
  - get: resource-repo
    trigger: true
  - put: resource-image
    params:
      build: resource-repo

resources:
- name: resource-repo
  type: git
  source:
    uri: https://github.com/EngineerBetter/cf-app-info-resource
    branch: master

- name: resource-image
  type: docker-image
  source:
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-repository}}
