#!/bin/sh
#set -ueo pipefail

#exec 3>&1 # make stdout available as fd 3 for the result
#exec 1>&2 # redirect all output to stderr for logging

echo '[ { "ref": "fubar" } ]' #>&3

#echo "[ { \"ref\": \"$(/opt/resource/fetch | { md5sum || md5; } 2>/dev/null | cut -f1 -d' ')\" } ]"
