#!/usr/bin/env bash
[ "$VERBOSE" ] && set -x
set -ueo pipefail

JQ_ARGS="-r --compact-output --monochrome-output"

INPUT="$(jq $JQ_ARGS .)"

echo "$INPUT" >&2

input() {
  echo "$INPUT" | jq $JQ_ARGS "$@"
}

SSL=""
[ "$(input .source.skip_ssl_validation)" = "true" ] && SSL="--skip-ssl-validation"
CF_API=$(input .source.api)
CF_USER=$(input .source.username)
CF_PASS=$(input .source.password)
CF_ORG=$(input .source.organization)
CF_SPACE=$(input .source.space)

LOGIN='login -a "$CF_API" -u "$CF_USER" -p "$CF_PASS" -o "$CF_ORG" -s "$CF_SPACE" $SSL'

eval "cf ${LOGIN} 1>&2"

GUID=$(cf app $(input .source.app_name) --guid)

cf curl /v2/apps/${GUID}/stats | jq $JQ_ARGS '{ uris: ."0".stats.uris }'
